- name: Install python plugin for asdf
  command: asdf plugin add python
  register: asdf_plugin_add_out
  changed_when: "'already added' not in asdf_plugin_add_out.stderr"
  failed_when: false

- name: Installing python versions via asdf
  loop:
    - 3.11.0
    - 3.10.8
  command: asdf install python {{ item }}
  register: asdf_install_out
  changed_when: "'is already installed' not in asdf_install_out.stdout"
