- brew:
    - "borgbackup" # Deduplicating archiver with compression and authenticated encryption
    - "yq" # Process YAML documents from the CLI

- create:
    - ~/.config/backups

- link:
    ~/.config/backups/ignore: ignore
    ~/.config/backups/config.yaml: backups-config.yaml
    ~/.local/bin/run-backup: run-backup.sh

- shell:
    - description: Check config file
      command: |-
        config_file="$HOME/.config/backups/config.yaml"

        if [[ ! -f $config_file ]]; then
          print "Config file is missing:\n  $config_file"
          exit 1
        fi

        chmod 400 $config_file

- crontab:
    - time: "0 * * * *" # every hour
      command: PATH="$HOME:/.local/bin:/usr/local/bin:$PATH" run-backup
